// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "AHRS.h"
#include "../RobotMap.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Drivetrain: public PIDSubsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> frontLeft;
	std::shared_ptr<CANTalon> frontRight;
	std::shared_ptr<CANTalon> rearLeft;
	std::shared_ptr<CANTalon> rearRight;
	std::shared_ptr<CANTalon> frontStrafe;
	std::shared_ptr<CANTalon> rearStrafe;
	std::shared_ptr<AHRS> ahrs;
	std::shared_ptr<Encoder> encoderRearLeft;
	std::shared_ptr<Encoder> encoderRearRight;
	std::shared_ptr<Encoder> encoderRightStrafe;
	std::shared_ptr<PIDController> pIDControllerDrivetrain;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Drivetrain();
	void InitDefaultCommand();
	void DrivingWithJoystick();
	void NormalizeInputs(float&,float&,float&,float&);
	float SmoothMotion(float motorSpeed, float speed, float accelLim);
	bool fieldOrient;
	void SetFieldOrient(bool);
	bool GetFieldOrient();
	double* FieldOriented(double, double, double);
	bool whileAnglePIDDriving = false;
	float leftSpeed,rightSpeed,frontStrafeSpeed,rearStrafeSpeed;
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void AllignWithGearPeg();
	double x;
	double y;
	double springX = 0;
	double springY = 0;
	double centerX = 200;
	double centerY = 320;




	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
