// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Drivetrain: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> frontLeft;
	std::shared_ptr<CANTalon> frontRight;
	std::shared_ptr<CANTalon> rearLeft;
	std::shared_ptr<CANTalon> rearRight;
	std::shared_ptr<CANTalon> frontStrafe;
	std::shared_ptr<CANTalon> rearStrafe;
	std::shared_ptr<AHRS> ahrs;
	std::shared_ptr<Encoder> encoderFrontLeft;
	std::shared_ptr<Encoder> encoderFrontRight;
	std::shared_ptr<Encoder> encoderRightStrafe;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Drivetrain();
	void InitDefaultCommand();
	void DrivingWithJoystick();
	void NormalizeInputs(float&,float&,float&,float&);
	float SmoothMotion(std::shared_ptr<CANTalon>, float speed, float accelLim);
	bool fieldOrient;
	void SetFieldOrient(bool);
	bool GetFieldOrient();


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
