// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"

/*AutoForward::AutoForward(float speed) {
	Requires(Robot::drivetrain);
		this->speed = speed;
		time= 5;
}*/
AutoForward::AutoForward(float speed, float time) {
	Requires(Robot::drivetrain.get());
		this->speed = speed;
		this->time = time;
}

// Called just before this Command runs the first time
void AutoForward::Initialize() {
	time = 5;
	SetTimeout(time);
}

// Called repeatedly when this Command is scheduled to run
void AutoForward::Execute() {
	speed = 1;
	RobotMap::drivetrainFrontLeft->Set(speed);
	RobotMap::drivetrainRearLeft->Set(speed);
	RobotMap::drivetrainFrontRight->Set(-speed);
	RobotMap::drivetrainRearRight->Set(-speed);

}

// Make this return true when this Command no longer needs to run execute()
bool AutoForward::IsFinished() {
	return IsTimedOut();
}

// Called once after isFinished returns true
void AutoForward::End() {
	RobotMap::drivetrainFrontLeft->Set(0);
	RobotMap::drivetrainRearLeft->Set(0);
	RobotMap::drivetrainFrontRight->Set(0);
	RobotMap::drivetrainRearRight->Set(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoForward::Interrupted() {

}
