// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ChangeMode.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ChangeMode::ChangeMode(int mode): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	this->mode = mode;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ChangeMode::Initialize() {

}

// Called repeatedly when this Command is scheduled to run


void ChangeMode::Execute() {

	if (mode==TRACTION){

	Robot::pneumatics->ChangeDriveMode();
	}

	if (mode==8){
		RobotMap::drivetrainAHRS->Reset();
	}

	if (mode==FIELD_ORIENTED) {
		if (Robot::drivetrain->GetFieldOrient()){
			Robot::drivetrain->SetFieldOrient(false);
		}
		else {
			Robot::drivetrain->SetFieldOrient(true);
		}
	}

}

// Make this return true when this Command no longer needs to run execute()
bool ChangeMode::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ChangeMode::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChangeMode::Interrupted() {

}
