// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::drivetrainFrontLeft;
std::shared_ptr<CANTalon> RobotMap::drivetrainFrontRight;
std::shared_ptr<CANTalon> RobotMap::drivetrainRearLeft;
std::shared_ptr<CANTalon> RobotMap::drivetrainRearRight;
std::shared_ptr<CANTalon> RobotMap::drivetrainFrontStrafe;
std::shared_ptr<CANTalon> RobotMap::drivetrainRearStrafe;
std::shared_ptr<DoubleSolenoid> RobotMap::pneumaticsFrontLeft;
std::shared_ptr<DoubleSolenoid> RobotMap::pneumaticsFrontRight;
std::shared_ptr<DoubleSolenoid> RobotMap::pneumaticsRearLeft;
std::shared_ptr<DoubleSolenoid> RobotMap::pneumaticsRearRight;
std::shared_ptr<DoubleSolenoid> RobotMap::pneumaticsFrontStrafe;
std::shared_ptr<DoubleSolenoid> RobotMap::pneumaticsRearStrafe;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    drivetrainFrontLeft.reset(new CANTalon(5));
    lw->AddActuator("Drivetrain", "Front Left", drivetrainFrontLeft);
    
    drivetrainFrontRight.reset(new CANTalon(3));
    lw->AddActuator("Drivetrain", "Front Right", drivetrainFrontRight);
    
    drivetrainRearLeft.reset(new CANTalon(6));
    lw->AddActuator("Drivetrain", "Rear Left", drivetrainRearLeft);
    
    drivetrainRearRight.reset(new CANTalon(2));
    lw->AddActuator("Drivetrain", "Rear Right", drivetrainRearRight);
    
    drivetrainFrontStrafe.reset(new CANTalon(4));
    lw->AddActuator("Drivetrain", "Front Strafe", drivetrainFrontStrafe);
    
    drivetrainRearStrafe.reset(new CANTalon(1));
    lw->AddActuator("Drivetrain", "Rear Strafe", drivetrainRearStrafe);
    
    pneumaticsFrontLeft.reset(new DoubleSolenoid(0, 0, 1));
    lw->AddActuator("Pneumatics", "Front Left", pneumaticsFrontLeft);
    
    pneumaticsFrontRight.reset(new DoubleSolenoid(0, 2, 3));
    lw->AddActuator("Pneumatics", "Front Right", pneumaticsFrontRight);
    
    pneumaticsRearLeft.reset(new DoubleSolenoid(0, 4, 5));
    lw->AddActuator("Pneumatics", "Rear Left", pneumaticsRearLeft);
    
    pneumaticsRearRight.reset(new DoubleSolenoid(0, 6, 7));
    lw->AddActuator("Pneumatics", "Rear Right", pneumaticsRearRight);
    
    pneumaticsFrontStrafe.reset(new DoubleSolenoid(1, 0, 1));
    lw->AddActuator("Pneumatics", "Front Strafe", pneumaticsFrontStrafe);
    
    pneumaticsRearStrafe.reset(new DoubleSolenoid(1, 2, 3));
    lw->AddActuator("Pneumatics", "Rear Strafe", pneumaticsRearStrafe);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
