// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "AHRS.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> drivetrainFrontLeft;
	static std::shared_ptr<CANTalon> drivetrainFrontRight;
	static std::shared_ptr<CANTalon> drivetrainRearLeft;
	static std::shared_ptr<CANTalon> drivetrainRearRight;
	static std::shared_ptr<CANTalon> drivetrainFrontStrafe;
	static std::shared_ptr<CANTalon> drivetrainRearStrafe;
	static std::shared_ptr<DoubleSolenoid> pneumaticsFrontLeft;
	static std::shared_ptr<DoubleSolenoid> pneumaticsFrontRight;
	static std::shared_ptr<DoubleSolenoid> pneumaticsRearLeft;
	static std::shared_ptr<DoubleSolenoid> pneumaticsRearRight;
	static std::shared_ptr<DoubleSolenoid> pneumaticsFrontStrafe;
	static std::shared_ptr<DoubleSolenoid> pneumaticsRearStrafe;
	static std::shared_ptr<AHRS> drivetrainAHRS;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
